### ISSUE TITLE
2.0.0 TODO list

### ISSUE THREAD

**Issue by SeaDve** [SeaDve/Kooha#75]
#### Major
- [x] #112
- [x] #113
- [x] #60
- [x] Disable gui audio settings when format is GIF
- [x] Remove session bus (see: https://github.com/SeaDve/AreaSelector/issues/1)
- [x] Fix broken fractional scaling selection
- [x] Area selection implementation on Wayland without relying on org.gnome.shell.Screenshot
- [x] Crashes on selection mode when there is a delay
#### Minor
- [ ] #114
- [x] Improve VAAPI pipeline
- [x] The switcher shouldn't be untoggled (possibly fixed in GTK v4.3.2)
- [x] Add F10 shortcut to the primary menu (waiting for GTK v4.3.1) (Fix this too with Mousai and Breathing)
- [x] Allow multisource select
- [x] Set the portal window modal, when this happen, we don't have to bind sensitive to is-readying
- [x] Properly send window identifier in screencast_portal
- [x] More efficient gif recording to avoid delayed stopped on higher res
- [x] Improve audio settings disablement when format is gif
- [x] Window can be resize after it is set visible to false then true again (Fixed as we don't hide window anymore, but gtk issue)
- [x] Don't hide window, as it doesn't save the window location. Instead, set the record button insensitive.
- [x] Area selector should start instantly
- [x] Timer needs timing polish
- [x] Don't use lambda in line 63 `pipeline_builder`
#### Very minor
- [x] Update readme/appdata and screenshots
- [x] Moved to #87
- [x] use offline building for gst-plugin-gif
- [x] Check if there is an issue if the recording is stopped quickly
- [x] Check if closing the app too fast may cause corrupting the video
- [x] Clicking too fast may cause weird harmless issue after cancelling delay
#### Possible Aditional features
- [x] GIF/APNG support
- [x] VAAPI support
- [x] #115
- [x] #116
#### AreaSelector specific (Some seems impossible on wayland D: )
- [x] Set as keep above
- [x] #117
- [x] There should be fade (not window) animation when closing the selector window
- [x] Don't show on taskbar or overview
